plugins:
  - jekyll-remote-theme
###remote_theme: benbalter/retlab
remote_theme: http[s]://github.<Enterprise>.com/readthedocs/sphinx_rtd_theme
##remote_theme:  coderefinery/sphinx-lesson-template
###readthedocs/sphinx_rtd_theme 
